# Generated by Django 5.2.5 on 2025-09-23 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VisaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('HOLD', 'Hold'), ('INVITED', 'Invited'), ('LODGED', 'Lodged'), ('CLOSED', 'Closed')], max_length=255)),
                ('points', models.IntegerField()),
                ('count', models.IntegerField()),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.occupation')),
                ('visa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.visatype')),
            ],
        ),
    ]
