# Generated by Django 5.2.5 on 2025-09-23 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='visadata',
            name='month_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.monthyear'),
        ),
    ]
