# Generated by Django 5.2.5 on 2025-09-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('total_rows', models.IntegerField(blank=True, null=True)),
                ('processed_rows', models.IntegerField(blank=True, null=True)),
                ('errors_count', models.IntegerField(blank=True, null=True)),
                ('errors_detail', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Excel Import',
                'verbose_name_plural': 'Excel Imports',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
