name: Deploy to Heroku

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Check if frontend exists and install dependencies
      run: |
        if [ -f "frontend/package.json" ]; then
          echo "Frontend found, installing dependencies..."
          cd frontend
          npm install
          npm run build
          cd ..
          mkdir -p static
          cp -r frontend/build/* static/ || echo "No build output to copy"
        else
          echo "No frontend directory found, skipping frontend build"
          mkdir -p static
        fi

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput

    - name: Setup Heroku CLI
      uses: extractions/setup-heroku@v1
      with:
        api-key: ${{ secrets.HEROKU_API_KEY }}

    - name: Deploy to Heroku
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        git add .
        git commit -m "Deploy from GitHub Actions" || echo "No changes to commit"
        git push heroku HEAD:main --force